# Jekyll configuration

name: mkyforever
description: 
  Keep learning forever...<br />
  Keep walking forever...<br />
  Keep seeing forever...<br />
  
website: www.makuiyu.cn 

# url is currently only used only for the RSS feed in feed.xml
url: http://makuiyu.cn 

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: 

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

disqus: 'makuiyu'
comments: true

permalink: /:year/:month/:title
paginate: 10
excerpt_separator: <!--more-->

safe: false

highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
